"use client";
import { useEffect, useRef, useState } from "react";
import { Certificate } from "./certificate";
import { configSchema, fieldDescriptors, presetDefaults, STORAGE_KEY, type CertificateConfig } from "./certificate-config";
import { capture, download, downloadPdf, filename } from "./export";

const button = "rounded-md border border-[#cfc7ba] bg-white px-3 py-2 text-sm font-semibold text-[#243653] shadow-sm transition hover:bg-[#f4efe7] disabled:cursor-wait disabled:opacity-60";

export default function Home() {
  const [config, setConfig] = useState<CertificateConfig>(presetDefaults);
  const [ready, setReady] = useState(false); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState("");
  const [overflow, setOverflow] = useState<string[]>([]); const [scale, setScale] = useState(1);
  const previewRef = useRef<HTMLDivElement>(null); const fileRef = useRef<HTMLInputElement>(null); const shellRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const timer = setTimeout(() => { try { const saved = localStorage.getItem(STORAGE_KEY); if (saved) { const parsed = configSchema.safeParse(JSON.parse(saved)); if (parsed.success) setConfig(parsed.data); else setNotice("The saved draft was invalid, so the preset was restored."); } } catch { setNotice("Automatic saving is unavailable in this browser."); } setReady(true); }, 0); return () => clearTimeout(timer); }, []);
  useEffect(() => { if (!ready) return; const timer = setTimeout(() => { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(config)); } catch { setNotice("Automatic saving is unavailable in this browser."); } }, 350); return () => clearTimeout(timer); }, [config, ready]);
  useEffect(() => { const update = () => { if (shellRef.current) setScale(Math.min(1, shellRef.current.clientWidth / 990)); }; update(); const obs = new ResizeObserver(update); if (shellRef.current) obs.observe(shellRef.current); return () => obs.disconnect(); }, []);
  useEffect(() => { const id = requestAnimationFrame(() => { if (!previewRef.current) return; const nodes = Array.from(previewRef.current.querySelectorAll<HTMLElement>("[data-fit]")); setOverflow(nodes.filter((node) => node.scrollHeight > node.clientHeight + 2 || node.scrollWidth > node.clientWidth + 2).map((node) => node.dataset.fit || "text")); }); return () => cancelAnimationFrame(id); }, [config]);
  const updateField = (key: keyof CertificateConfig["fields"], value: string) => setConfig((c) => ({ ...c, fields: { ...c.fields, [key]: value } }));
  const updateSignature = (index: number, key: keyof CertificateConfig["signatures"][number], value: string) => setConfig((c) => ({ ...c, signatures: c.signatures.map((s, i) => i === index ? { ...s, [key]: value } : s) }));
  const guardReplace = () => !ready || window.confirm("Replace the current certificate with this source?");
  const saveSource = () => download(new Blob([JSON.stringify(config, null, 2)], { type: "application/json" }), `${filename(config.fields.recipientName)}.certificate.json`);
  const openSource = async (file: File) => { if (file.size > 100_000) { setNotice("Source files must be smaller than 100 KB."); return; } try { const parsed = configSchema.safeParse(JSON.parse(await file.text())); if (!parsed.success) throw new Error(); if (guardReplace()) { setConfig(parsed.data); setNotice("Source file opened."); } } catch { setNotice("Could not open that source file. Check that it is valid certificate JSON."); } };
  const exportFile = async (kind: "png" | "pdf") => { if (!previewRef.current || overflow.length) { setNotice("Shorten the highlighted text before downloading."); return; } setBusy(kind); try { const image = await capture(previewRef.current); const name = filename(config.fields.recipientName); if (kind === "png") download(image, `${name}.png`); else await downloadPdf(image, `${name}.pdf`); } catch { setNotice("The certificate could not be exported. Please try again."); } finally { setBusy(""); } };
  const reset = () => { if (guardReplace()) { setConfig(structuredClone(presetDefaults)); setNotice("Preset restored."); } };
  return <main className="app-shell"><header className="app-header"><div><div className="eyebrow">ROMAN CATHOLIC COLLEGE</div><h1>Certificate Builder</h1><p>RCC Appreciation · edit the wording, then download a finished certificate.</p></div><div className="header-actions"><button className={button} onClick={saveSource}>Save source</button><button className={button} onClick={() => fileRef.current?.click()}>Open source</button><input ref={fileRef} type="file" accept="application/json,.json,.certificate.json" className="sr-only" onChange={(e) => { const file = e.target.files?.[0]; if (file) void openSource(file); e.currentTarget.value = ""; }} /><button className={button} onClick={reset}>Reset</button></div></header>
    {notice && <div className="notice" role="status">{notice}<button onClick={() => setNotice("")} aria-label="Dismiss">×</button></div>}
    <div className="workspace"><aside className="editor-panel"><section><h2>School and headings</h2>{fieldDescriptors.slice(0, 5).map(([key, label]) => <Field key={key} label={label} value={config.fields[key]} onChange={(v) => updateField(key, v)} />)}</section><section><h2>Award details</h2>{fieldDescriptors.slice(5, 13).map(([key, label]) => <Field key={key} label={label} value={config.fields[key]} onChange={(v) => updateField(key, v)} multiline={key === "programLine"} />)}</section><section><h2>Signatures and date</h2><label className="control-label">Number of signatures<select value={config.signatureCount} onChange={(e) => setConfig((c) => ({ ...c, signatureCount: Number(e.target.value) }))}>{[1, 2, 3, 4].map((n) => <option key={n}>{n}</option>)}</select></label><label className="toggle"><input type="checkbox" checked={config.showSeal} onChange={(e) => setConfig((c) => ({ ...c, showSeal: e.target.checked }))} /> Show red seal</label>{config.signatures.map((signature, i) => <div className="signature-editor" key={i}><h3>Signature {i + 1}</h3><Field label="Name" value={signature.name} onChange={(v) => updateSignature(i, "name", v)} /><Field label="Role" value={signature.role} onChange={(v) => updateSignature(i, "role", v)} /><Field label="Organization" value={signature.organization} onChange={(v) => updateSignature(i, "organization", v)} /></div>)}<Field label="Date" value={config.fields.date} onChange={(v) => updateField("date", v)} /></section></aside><section className="preview-panel"><div className="preview-toolbar"><div><span className="eyebrow">LIVE PREVIEW</span><span className="fit-status">{overflow.length ? `${overflow.length} field${overflow.length > 1 ? "s" : ""} needs shortening` : "Ready to download"}</span></div><div className="download-actions"><button className="primary-button" disabled={!!busy || !!overflow.length} onClick={() => void exportFile("png")}>{busy === "png" ? "Preparing…" : "Download PNG"}</button><button className={button} disabled={!!busy || !!overflow.length} onClick={() => void exportFile("pdf")}>{busy === "pdf" ? "Preparing…" : "Download PDF"}</button></div></div><div className="preview-shell" ref={shellRef}><div className="preview-scale" style={{ transform: `scale(${scale})` }}><Certificate config={config} innerRef={previewRef} /></div></div></section></div></main>;
}
function Field({ label, value, onChange, multiline }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean }) { const props = { value, maxLength: 1000, onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => onChange(e.target.value) }; return <label className="control-label">{label}{multiline ? <textarea {...props} rows={2} /> : <input {...props} />}</label>; }
